/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.models;

import DBHandling.Consultor;
import DBHandling.Insertion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JuanDavid
 */
public class Institucion extends javax.swing.JDialog {

    Consultor search = new Consultor();
    Insertion add = new Insertion();
    DefaultTableModel modelo = new DefaultTableModel();
    String[] ini = {"Materia"};  
    DefaultTableModel modelo1 = new DefaultTableModel();
    String[] ini1 = {"Grado", "Curso", "Estudiantes"};  
    Table abrir = new Table(this);
    
    
    
    public Institucion(javax.swing.JFrame parent) {
        super(parent, true);
        initComponents();
        cmbConsGrados.removeAll();
        this.setLocationRelativeTo(null);
        txtLogro.setLineWrap(true);
        modelo = new DefaultTableModel(null, ini);
        tblMat.setModel(modelo);
        modelo1 = new DefaultTableModel(null, ini1);
        tblGrad.setModel(modelo1);
        try {
            search.selectToGradosAll(cmbMatGrad, jLabel2.getText());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        NewMat.setVisible(true);
        FindMat.setVisible(false);
        NewGrad.setVisible(false);
        FindGrad.setVisible(false);
        NewAnio.setVisible(false);
        NewLogro.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Option = new javax.swing.JPanel();
        btnNewMat = new javax.swing.JButton();
        btnFindMat = new javax.swing.JButton();
        btnFindMat1 = new javax.swing.JButton();
        btnFindMat2 = new javax.swing.JButton();
        Set = new javax.swing.JPanel();
        NewMat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMatGrad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        FindMat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbFindMat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMat = new javax.swing.JTable();
        NewGrad = new javax.swing.JPanel();
        Grad = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbGrad = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        Curso = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbConsGrados = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        FindGrad = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGrad = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NewAnio = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        NewLogro = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLogro = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Option2 = new javax.swing.JPanel();
        btnNewGrad = new javax.swing.JButton();
        btnFindGrad = new javax.swing.JButton();
        btnNewYear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnNewMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddMat (64x64).png"))); // NOI18N
        btnNewMat.setText("Nueva Materia");
        btnNewMat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewMat.setIconTextGap(10);
        btnNewMat.setPreferredSize(new java.awt.Dimension(81, 85));
        btnNewMat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNewMat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMatActionPerformed(evt);
            }
        });

        btnFindMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FindMat (64x64).png"))); // NOI18N
        btnFindMat.setText("Buscar Materia");
        btnFindMat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindMat.setIconTextGap(10);
        btnFindMat.setPreferredSize(new java.awt.Dimension(81, 85));
        btnFindMat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFindMat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFindMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMatActionPerformed(evt);
            }
        });

        btnFindMat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewLog (64x64).png"))); // NOI18N
        btnFindMat1.setText("Nuevo Logro");
        btnFindMat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindMat1.setIconTextGap(10);
        btnFindMat1.setPreferredSize(new java.awt.Dimension(81, 85));
        btnFindMat1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFindMat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFindMat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMat1ActionPerformed(evt);
            }
        });

        btnFindMat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewGrad (64x64).png"))); // NOI18N
        btnFindMat2.setText("Mostar Logros");
        btnFindMat2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindMat2.setIconTextGap(10);
        btnFindMat2.setPreferredSize(new java.awt.Dimension(81, 85));
        btnFindMat2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFindMat2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFindMat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionLayout = new javax.swing.GroupLayout(Option);
        Option.setLayout(OptionLayout);
        OptionLayout.setHorizontalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewMat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindMat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFindMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OptionLayout.setVerticalGroup(
            OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFindMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindMat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewMat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewMat.setMaximumSize(new java.awt.Dimension(496, 291));
        NewMat.setMinimumSize(new java.awt.Dimension(496, 291));
        NewMat.setPreferredSize(new java.awt.Dimension(246, 309));

        jLabel1.setText("Año Lectivo");

        jLabel2.setText("2015");

        jLabel3.setText("Grado");

        jLabel4.setText("Nombre de la Materia");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Check (32x32).png"))); // NOI18N
        jButton4.setText("Crear");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setIconTextGap(2);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.setMaximumSize(new java.awt.Dimension(61, 61));
        jButton4.setMinimumSize(new java.awt.Dimension(61, 61));
        jButton4.setPreferredSize(new java.awt.Dimension(61, 61));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewMatLayout = new javax.swing.GroupLayout(NewMat);
        NewMat.setLayout(NewMatLayout);
        NewMatLayout.setHorizontalGroup(
            NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(NewMatLayout.createSequentialGroup()
                        .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMatGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel4)
                    .addComponent(txtMat))
                .addGap(48, 48, 48)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        NewMatLayout.setVerticalGroup(
            NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewMatLayout.createSequentialGroup()
                        .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NewMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMatGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        FindMat.setMaximumSize(new java.awt.Dimension(496, 291));
        FindMat.setMinimumSize(new java.awt.Dimension(496, 291));
        FindMat.setPreferredSize(new java.awt.Dimension(496, 374));

        jLabel5.setText("Año Lectivo");

        jLabel6.setText("2015");

        jLabel7.setText("Grado");

        cmbFindMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFindMatActionPerformed(evt);
            }
        });

        tblMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMat);

        javax.swing.GroupLayout FindMatLayout = new javax.swing.GroupLayout(FindMat);
        FindMat.setLayout(FindMatLayout);
        FindMatLayout.setHorizontalGroup(
            FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(FindMatLayout.createSequentialGroup()
                        .addGroup(FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFindMat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FindMatLayout.setVerticalGroup(
            FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(FindMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbFindMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        NewGrad.setMaximumSize(new java.awt.Dimension(496, 291));
        NewGrad.setMinimumSize(new java.awt.Dimension(496, 291));

        Grad.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Grado"));

        jLabel8.setText("Año Lectivo");

        jLabel9.setText("2015");

        jLabel10.setText("Grado");

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Check (32x32).png"))); // NOI18N
        jButton5.setText("Crear");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(2);
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton5.setMaximumSize(new java.awt.Dimension(61, 61));
        jButton5.setMinimumSize(new java.awt.Dimension(61, 61));
        jButton5.setPreferredSize(new java.awt.Dimension(61, 61));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GradLayout = new javax.swing.GroupLayout(Grad);
        Grad.setLayout(GradLayout);
        GradLayout.setHorizontalGroup(
            GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GradLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(GradLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GradLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        GradLayout.setVerticalGroup(
            GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GradLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(GradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Curso.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Curso"));

        jLabel11.setText("Año Lectivo");

        jLabel15.setText("2015");

        jLabel16.setText("Grado");

        jLabel17.setText("Curso");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Check (32x32).png"))); // NOI18N
        jButton6.setText("Crear");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(2);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.setMaximumSize(new java.awt.Dimension(61, 61));
        jButton6.setMinimumSize(new java.awt.Dimension(61, 61));
        jButton6.setPreferredSize(new java.awt.Dimension(61, 61));
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CursoLayout = new javax.swing.GroupLayout(Curso);
        Curso.setLayout(CursoLayout);
        CursoLayout.setHorizontalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursoLayout.createSequentialGroup()
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbConsGrados, 0, 56, Short.MAX_VALUE)
                        .addComponent(txtCurso))
                    .addComponent(jLabel15))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CursoLayout.setVerticalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbConsGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout NewGradLayout = new javax.swing.GroupLayout(NewGrad);
        NewGrad.setLayout(NewGradLayout);
        NewGradLayout.setHorizontalGroup(
            NewGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGradLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NewGradLayout.setVerticalGroup(
            NewGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewGradLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Grad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Curso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel12.setText("Año Lectivo");

        jLabel13.setText("2015");

        tblGrad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblGrad);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("* Solo se muestran grados con estudiantes inscritos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/View (64x64).png"))); // NOI18N
        jButton1.setText("Ver");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FindGradLayout = new javax.swing.GroupLayout(FindGrad);
        FindGrad.setLayout(FindGradLayout);
        FindGradLayout.setHorizontalGroup(
            FindGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindGradLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FindGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(FindGradLayout.createSequentialGroup()
                        .addGroup(FindGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FindGradLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindGradLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FindGradLayout.setVerticalGroup(
            FindGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindGradLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FindGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Check (32x32).png"))); // NOI18N
        jButton7.setText("Crear");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(2);
        jButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton7.setMaximumSize(new java.awt.Dimension(61, 61));
        jButton7.setMinimumSize(new java.awt.Dimension(61, 61));
        jButton7.setPreferredSize(new java.awt.Dimension(61, 61));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel18.setText("Escriba Año Lectivo");

        javax.swing.GroupLayout NewAnioLayout = new javax.swing.GroupLayout(NewAnio);
        NewAnio.setLayout(NewAnioLayout);
        NewAnioLayout.setHorizontalGroup(
            NewAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAnioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(NewAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        NewAnioLayout.setVerticalGroup(
            NewAnioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAnioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewAnioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel19.setText("Año Lectivo");

        jLabel20.setText("Año Lectivo");

        jLabel21.setText("Grado");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1", "2", "3", "4", "5" }));

        jLabel22.setText("Materia");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        txtLogro.setColumns(20);
        txtLogro.setRows(5);
        jScrollPane3.setViewportView(txtLogro);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Check (32x32).png"))); // NOI18N
        jButton8.setText("Crear");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setIconTextGap(2);
        jButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton8.setMaximumSize(new java.awt.Dimension(61, 61));
        jButton8.setMinimumSize(new java.awt.Dimension(61, 61));
        jButton8.setPreferredSize(new java.awt.Dimension(61, 61));
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel23.setText("Ingrese Logro");

        javax.swing.GroupLayout NewLogroLayout = new javax.swing.GroupLayout(NewLogro);
        NewLogro.setLayout(NewLogroLayout);
        NewLogroLayout.setHorizontalGroup(
            NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewLogroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NewLogroLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel20))
                        .addGroup(NewLogroLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NewLogroLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        NewLogroLayout.setVerticalGroup(
            NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewLogroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewLogroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SetLayout = new javax.swing.GroupLayout(Set);
        Set.setLayout(SetLayout);
        SetLayout.setHorizontalGroup(
            SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewMat, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FindMat, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FindGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewLogro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        SetLayout.setVerticalGroup(
            SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewMat, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FindMat, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(FindGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NewLogro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnNewGrad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewGrad (64x64).png"))); // NOI18N
        btnNewGrad.setText("Nuevo Grado");
        btnNewGrad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewGrad.setIconTextGap(10);
        btnNewGrad.setPreferredSize(new java.awt.Dimension(81, 85));
        btnNewGrad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNewGrad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGradActionPerformed(evt);
            }
        });

        btnFindGrad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ConsGrad (64x64).png"))); // NOI18N
        btnFindGrad.setText("Mostrar Grado");
        btnFindGrad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindGrad.setIconTextGap(10);
        btnFindGrad.setPreferredSize(new java.awt.Dimension(81, 85));
        btnFindGrad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFindGrad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFindGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindGradActionPerformed(evt);
            }
        });

        btnNewYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/NewYear (64x64).png"))); // NOI18N
        btnNewYear.setText("Nuevo Año");
        btnNewYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewYear.setIconTextGap(10);
        btnNewYear.setPreferredSize(new java.awt.Dimension(81, 85));
        btnNewYear.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNewYear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Option2Layout = new javax.swing.GroupLayout(Option2);
        Option2.setLayout(Option2Layout);
        Option2Layout.setHorizontalGroup(
            Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFindGrad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnNewGrad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Option2Layout.setVerticalGroup(
            Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFindGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Option2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Option2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMatActionPerformed
        NewMat.setVisible(true);
        FindMat.setVisible(false);
        NewGrad.setVisible(false);
        FindGrad.setVisible(false);
        NewAnio.setVisible(false);
        NewLogro.setVisible(false);
        cmbMatGrad.removeAllItems();
        cmbMatGrad.addItem("-");
        try {
            search.selectToGradosAll(cmbMatGrad, jLabel2.getText());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnNewMatActionPerformed

    private void btnFindMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMatActionPerformed
        NewMat.setVisible(false);
        FindMat.setVisible(true);
        NewGrad.setVisible(false);
        FindGrad.setVisible(false);
        NewAnio.setVisible(false);
        NewLogro.setVisible(false);
        cmbFindMat.removeAllItems();
        cmbFindMat.addItem("-");
        try {
            search.selectToGradosAll(cmbFindMat, jLabel2.getText());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_btnFindMatActionPerformed

    private void btnNewGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGradActionPerformed
        NewMat.setVisible(false);
        FindMat.setVisible(false);
        NewGrad.setVisible(true);
        FindGrad.setVisible(false);
        NewAnio.setVisible(false);
        NewLogro.setVisible(false);
        cmbConsGrados.removeAllItems();
        cmbConsGrados.addItem("-");
        try {
            search.selectToGradosAll(cmbConsGrados, jLabel15.getText());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnNewGradActionPerformed

    private void btnFindGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindGradActionPerformed
        NewMat.setVisible(false);
        FindMat.setVisible(false);
        NewGrad.setVisible(false);
        FindGrad.setVisible(true);
        NewAnio.setVisible(false);
        NewLogro.setVisible(false);
        modelo1 = new DefaultTableModel(null, ini1);
        tblGrad.setModel(modelo1);
        try {
            search.selectToGrados(tblGrad, modelo1);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnFindGradActionPerformed

    private void btnNewYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewYearActionPerformed
        NewMat.setVisible(false);
        FindMat.setVisible(false);
        NewGrad.setVisible(false);
        FindGrad.setVisible(false);
        NewAnio.setVisible(true);
        NewLogro.setVisible(false);
    }//GEN-LAST:event_btnNewYearActionPerformed

    private void btnFindMat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMat1ActionPerformed
        NewMat.setVisible(false);
        FindMat.setVisible(false);
        NewGrad.setVisible(false);
        FindGrad.setVisible(false);
        NewAnio.setVisible(false);
        NewLogro.setVisible(true);
    }//GEN-LAST:event_btnFindMat1ActionPerformed

    private void btnFindMat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindMat2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            if(cmbGrad.getSelectedItem().toString() != "-"){   
                if(add.insertToGrados(cmbGrad.getSelectedItem().toString(), jLabel9.getText()) == true){
                    JOptionPane.showMessageDialog(null, "Creación Exitosa");
                    cmbConsGrados.removeAllItems();
                    cmbConsGrados.addItem("-");
                    try {
                        search.selectToGradosAll(cmbConsGrados, jLabel15.getText());
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Algo salio mal");
                }                
            }else{
                JOptionPane.showMessageDialog(null, "'-' No es una seleccion valida");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getErrorCode());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            if(cmbConsGrados.getSelectedItem().toString() != "-"){  
                if(add.insertToCursos(jLabel15.getText(),cmbConsGrados.getSelectedItem().toString(), txtCurso.getText()) == true){
                    JOptionPane.showMessageDialog(null, "Creación Exitosa");
                }else{
                    JOptionPane.showMessageDialog(null, "Algo salio mal");
                }                 
            } else{
                JOptionPane.showMessageDialog(null, "'-' No es una seleccion valida");
            }
        } catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if(cmbMatGrad.getSelectedItem().toString() != "-"){
                if(add.insertToMaterias(txtMat.getText(), cmbMatGrad.getSelectedItem().toString(), jLabel2.getText()) == true){
                    JOptionPane.showMessageDialog(null, "Creación Exitosa");
                }else{
                    JOptionPane.showMessageDialog(null, "Algo salio mal");
                }
            }else {
                JOptionPane.showMessageDialog(null, "'-' No es una seleccion valida");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbFindMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFindMatActionPerformed
        modelo = new DefaultTableModel(null, ini);
        tblMat.setModel(modelo);
        try {
            search.selectToMaterias(tblMat, modelo, jLabel6.getText(), cmbFindMat.getSelectedItem().toString());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cmbFindMatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = tblGrad.getSelectedRow();
        if(i != -1){
            try {
                abrir.generatorTable(tblGrad.getValueAt(i, 0).toString(), tblGrad.getValueAt(i, 1).toString(), jLabel13.getText());
                abrir.setVisible(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else{
            JOptionPane.showMessageDialog(null, "Por favor haga una seleccion en la tabla");
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Institucion(new javax.swing.JFrame()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Curso;
    private javax.swing.JPanel FindGrad;
    private javax.swing.JPanel FindMat;
    private javax.swing.JPanel Grad;
    private javax.swing.JPanel NewAnio;
    private javax.swing.JPanel NewGrad;
    private javax.swing.JPanel NewLogro;
    private javax.swing.JPanel NewMat;
    private javax.swing.JPanel Option;
    private javax.swing.JPanel Option2;
    private javax.swing.JPanel Set;
    private javax.swing.JButton btnFindGrad;
    private javax.swing.JButton btnFindMat;
    private javax.swing.JButton btnFindMat1;
    private javax.swing.JButton btnFindMat2;
    private javax.swing.JButton btnNewGrad;
    private javax.swing.JButton btnNewMat;
    private javax.swing.JButton btnNewYear;
    private javax.swing.JComboBox cmbConsGrados;
    private javax.swing.JComboBox cmbFindMat;
    private javax.swing.JComboBox cmbGrad;
    private javax.swing.JComboBox cmbMatGrad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblGrad;
    private javax.swing.JTable tblMat;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextArea txtLogro;
    private javax.swing.JTextField txtMat;
    // End of variables declaration//GEN-END:variables
}
