/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBHandling.Consultor;
import Models.Bridge;
import Models.Encrypt;
import View.models.Consultar;
import View.models.Institucion;
import View.models.Users;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import View.models.Registro_alumnos;
import View.models.Registro_docentes;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author JuanDavid
 */
public class Principal extends javax.swing.JFrame {
    
    boolean state = false;
    String[] GV_data;
    Consultor search = new Consultor();
    Bridge message = new Bridge();
    Encrypt clue = new Encrypt(); 
    
    public Principal() throws FileNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        Welcome.setVisible(true);
        Secretaria.setVisible(false);
        boolean rest = false;
        while(rest != true){
            rest = reader();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passUser = new javax.swing.JPasswordField();
        btnConect = new javax.swing.JButton();
        Principal = new javax.swing.JPanel();
        Secretaria = new javax.swing.JPanel();
        Estudiantes = new javax.swing.JPanel();
        btnMat2 = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnMat1 = new javax.swing.JButton();
        Profesores = new javax.swing.JPanel();
        btnMat3 = new javax.swing.JButton();
        btnMat4 = new javax.swing.JButton();
        Admon = new javax.swing.JPanel();
        btnMat5 = new javax.swing.JButton();
        btnMat6 = new javax.swing.JButton();
        Welcome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setBackground(new java.awt.Color(255, 255, 255));

        Login.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setText("Usuario");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña");

        btnConect.setText("Conectar");
        btnConect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUser)
                    .addComponent(passUser)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btnConect, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(btnConect)
                .addContainerGap())
        );

        Secretaria.setBorder(javax.swing.BorderFactory.createTitledBorder("Secretaria"));
        Secretaria.setForeground(new java.awt.Color(255, 255, 255));

        Estudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes"));

        btnMat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserError (64x64).png"))); // NOI18N
        btnMat2.setText("Inhabilitar");
        btnMat2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat2.setIconTextGap(10);
        btnMat2.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMat2ActionPerformed(evt);
            }
        });

        btnMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FindUser_2 (64x64).png"))); // NOI18N
        btnMateria.setText("Consultar");
        btnMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMateria.setIconTextGap(10);
        btnMateria.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMateria.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMateria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });

        btnMat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddUser (64x64).png"))); // NOI18N
        btnMat1.setText("Matricular");
        btnMat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat1.setIconTextGap(10);
        btnMat1.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EstudiantesLayout = new javax.swing.GroupLayout(Estudiantes);
        Estudiantes.setLayout(EstudiantesLayout);
        EstudiantesLayout.setHorizontalGroup(
            EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstudiantesLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(btnMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EstudiantesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
        );
        EstudiantesLayout.setVerticalGroup(
            EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EstudiantesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Profesores.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesores"));

        btnMat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddUser (64x64).png"))); // NOI18N
        btnMat3.setText("Registrar");
        btnMat3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat3.setIconTextGap(10);
        btnMat3.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMat3ActionPerformed(evt);
            }
        });

        btnMat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/FindUser_2 (64x64).png"))); // NOI18N
        btnMat4.setText("Consultar");
        btnMat4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat4.setIconTextGap(10);
        btnMat4.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout ProfesoresLayout = new javax.swing.GroupLayout(Profesores);
        Profesores.setLayout(ProfesoresLayout);
        ProfesoresLayout.setHorizontalGroup(
            ProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMat3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnMat4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        ProfesoresLayout.setVerticalGroup(
            ProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMat4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMat3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admon.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar"));

        btnMat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User (64x64).png"))); // NOI18N
        btnMat5.setText("Usuarios");
        btnMat5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat5.setIconTextGap(10);
        btnMat5.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMat5ActionPerformed(evt);
            }
        });

        btnMat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Institution (64x64).png"))); // NOI18N
        btnMat6.setText("Institucion");
        btnMat6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMat6.setIconTextGap(10);
        btnMat6.setPreferredSize(new java.awt.Dimension(81, 85));
        btnMat6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMat6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMat6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdmonLayout = new javax.swing.GroupLayout(Admon);
        Admon.setLayout(AdmonLayout);
        AdmonLayout.setHorizontalGroup(
            AdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMat5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnMat6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdmonLayout.setVerticalGroup(
            AdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdmonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMat6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMat5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SecretariaLayout = new javax.swing.GroupLayout(Secretaria);
        Secretaria.setLayout(SecretariaLayout);
        SecretariaLayout.setHorizontalGroup(
            SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecretariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Estudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SecretariaLayout.setVerticalGroup(
            SecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecretariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Admon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel3)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Secretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Secretaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean reader() throws FileNotFoundException{
        FileReader LV_fr = new FileReader("config.ini");
        BufferedReader LV_bf = new BufferedReader(LV_fr);
        try {
            String LV_read = LV_bf.readLine();
            GV_data = LV_read.split(",");
            return true;
        } catch (IOException ex) {
            ex.printStackTrace();
            return false;
        }
    }
    
    private void btnConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectActionPerformed
        /*Welcome.setVisible(false);
                Secretaria.setVisible(true);
                btnConect.setText("Desconectar");
                txtUser.setEditable(false);
                passUser.setEditable(false);*/
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        Date date = new Date();
        System.out.println(dateFormat.format(date)); //2014/08/06 15:59:48
        if(message.setter(GV_data) == true){
            state = !state;
            try {
                String[] s = search.selectToUsers(txtUser.getText(), clue.getStringMenssageDigest(clue.getStringMenssageDigest(clue.getStringMenssageDigest(passUser.getText(),"SHA-1"),"MD5"),"MD2"));
                this.setTitle("Bienvenido: "+s[0]+" "+s[1]+"   Acceso: "+s[2]);
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (NoSuchAlgorithmException ex) {
                ex.printStackTrace();
            }
            if(state == true){
                Welcome.setVisible(false);
                Secretaria.setVisible(true);
                btnConect.setText("Desconectar");
                txtUser.setEditable(false);
                passUser.setEditable(false);
            }else{
                btnConect.setText("Conectar");
                txtUser.setEditable(true);
                passUser.setEditable(true);
                passUser.removeAll();
                jLabel3.setText("Hasta Luego");
                this.setTitle("Principal");
                Welcome.setVisible(true);
                Secretaria.setVisible(false);
                message.deSetter(GV_data);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Los datos ingresados son no son correctos");
            passUser.removeAll();
        }  
    }//GEN-LAST:event_btnConectActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        Consultar abrir = new Consultar(this);
        abrir.setVisible(true);  
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnMat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMat5ActionPerformed
        Users abrir = new Users(this);
        abrir.setVisible(true);
    }//GEN-LAST:event_btnMat5ActionPerformed

    private void btnMat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMat6ActionPerformed
        Institucion abrir = new Institucion(this);
        abrir.setVisible(true);
    }//GEN-LAST:event_btnMat6ActionPerformed

    private void btnMat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMat1ActionPerformed
         Registro_alumnos abrir = new Registro_alumnos();
         abrir.setVisible(true);
    }//GEN-LAST:event_btnMat1ActionPerformed

    private void btnMat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMat3ActionPerformed
        Registro_docentes abrir = new Registro_docentes();
         abrir.setVisible(true);
                                
    }//GEN-LAST:event_btnMat3ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnMat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (FileNotFoundException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admon;
    private javax.swing.JPanel Estudiantes;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Profesores;
    private javax.swing.JPanel Secretaria;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton btnConect;
    private javax.swing.JButton btnMat1;
    private javax.swing.JButton btnMat2;
    private javax.swing.JButton btnMat3;
    private javax.swing.JButton btnMat4;
    private javax.swing.JButton btnMat5;
    private javax.swing.JButton btnMat6;
    private javax.swing.JButton btnMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passUser;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
